### ISSUE TITLE
settings.php should either add config.php or have an internal check (not both)

### ISSUE THREAD

**Issue by danmarsden** [andreasschenkel/moodle-report_rolessitemap#1]
https://github.com/andreasschenkel/moodle-report_rolessitemap/blob/master/settings.php#L28

the require_login and require (config.php) stuff shouldn't be needed here.

not a blocker - just messy...

**Comment by andreasschenkel** [comment]
I think the rows 
```
require_once(__DIR__ . '/../../config.php');
require_once($CFG->dirroot . '/' . $CFG->admin . '/roles/lib.php');
require_login();
```
are some old try and error stuff ... 
I will delete all three lines because they seems to be not necessary.
